language: generic
sudo: false
cache: apt

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libgit2-dev
          sources: &sources
            - r-packages-precise
            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.8
#    - env: CXX=clang++-3.8 CC=clang-3.8
#      addons:
#        apt:
#          packages:
#            - clang-3.8
#            - libgit2-dev
#          sources: *sources

script:
  - make -j$(nproc)
  - make run-tests
